server:
  port: 8090
spring:
  application:
    name: product-server
  cloud:
    config:
      discovery:
        enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study
    username: root
    password: wojiushiwo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
    fetch-registry: false
    register-with-eureka: true
